"""cambio modelo

Revision ID: a521eac6dc9c
Revises: f05a81dfa72d
Create Date: 2025-06-22 22:28:28.003577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a521eac6dc9c'
down_revision: Union[str, None] = 'f05a81dfa72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('carrera')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrera', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('auto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'estadoventa', ['estado_id'], ['id'])

    # ### end Alembic commands ###
