"""crear todo

Revision ID: def1c8c4ec10
Revises: 
Create Date: 2025-06-13 18:26:26.968383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def1c8c4ec10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_color_id'), 'color', ['id'], unique=False)
    op.create_table('combustible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combustible_id'), 'combustible', ['id'], unique=False)
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_id'), 'estado', ['id'], unique=False)
    op.create_table('estadov',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estadov_id'), 'estadov', ['id'], unique=False)
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marca_id'), 'marca', ['id'], unique=False)
    op.create_table('metodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodo_id'), 'metodo', ['id'], unique=False)
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendedor_id'), 'vendedor', ['id'], unique=False)
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelo_id'), 'modelo', ['id'], unique=False)
    op.create_table('auto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.Column('combustible_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['combustible_id'], ['combustible.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_id'), 'auto', ['id'], unique=False)
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrera', sa.String(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('metodo_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.Column('auto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auto_id'], ['auto.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['metodo_id'], ['metodo.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_id'), 'venta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venta_id'), table_name='venta')
    op.drop_table('venta')
    op.drop_index(op.f('ix_auto_id'), table_name='auto')
    op.drop_table('auto')
    op.drop_index(op.f('ix_modelo_id'), table_name='modelo')
    op.drop_table('modelo')
    op.drop_index(op.f('ix_vendedor_id'), table_name='vendedor')
    op.drop_table('vendedor')
    op.drop_index(op.f('ix_metodo_id'), table_name='metodo')
    op.drop_table('metodo')
    op.drop_index(op.f('ix_marca_id'), table_name='marca')
    op.drop_table('marca')
    op.drop_index(op.f('ix_estadov_id'), table_name='estadov')
    op.drop_table('estadov')
    op.drop_index(op.f('ix_estado_id'), table_name='estado')
    op.drop_table('estado')
    op.drop_index(op.f('ix_combustible_id'), table_name='combustible')
    op.drop_table('combustible')
    op.drop_index(op.f('ix_color_id'), table_name='color')
    op.drop_table('color')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
